name: Discord Update

on:
  schedule:
    - cron: '0 * * * *'  # jede Stunde
  workflow_dispatch:  # manuell starten möglich

jobs:
  discord_post:
    runs-on: ubuntu-latest
    steps:
      - name: Repo auschecken
        uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Abhängigkeiten installieren
        run: pip install discord-webhook requests

      - name: Discord Nachricht senden
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          RAW_JSON_URL: ${{ secrets.RAW_JSON_URL }}
        run: python discord_post.py
